POST http://localhost:5224/api/posts
Authorization: Bearer YOUR_JWT_TOKEN_HERE
Content-Type: application/json

{
  "title" : "Post title",
  "content": "Authenticated post"
}

###

GET http://localhost:5224/api/posts